repository: yveso/yveso.github.io
theme: jekyll-theme-tactile
author: Yves Oehlschläger
title: Yves schreibt
description: Ein Blog über dies und das und jenes
excerpt_separator: <!--more-->
baseurl: https://blog.yveso.de/
gems:
  - jekyll-feed
feed:
  path: atom.xml
