repository: yveso/yveso.github.io
theme: jekyll-theme-hacker
author: Yves Oehlschläger
title: Yves schreibt
description: Ein Blog über dies und das und jenes
excerpt_separator: <!--more-->
gems:
  - jekyll-feed
feed:
  path: atom.xml
